name: "Deploy"

on:
  workflow_dispatch: # manually triggered
  push:
    branches: [master]
    paths:
      - '**/*.java'
      - '**/*.toml'

jobs:
  build-deploy:
    if: github.repository_owner == 'alpine-network' && github.ref_name == 'master'

    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: "Prepare JDK"
        # https://github.com/actions/setup-java/releases
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: temurin
          java-version: 21
          check-latest: true

      - name: "Prepare Gradle"
        # https://github.com/gradle/actions/releases
        uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3
        with:
          validate-wrappers: true
          gradle-version: wrapper
          cache-disabled: false

      - name: "Build Project"
        run: ./gradlew build --full-stacktrace

      - name: "Publish to Maven"
        run: ./gradlew publishAllPublicationsToAlpineCloudRepository --full-stacktrace
        env:
          ALPINE_MAVEN_NAME: ${{ secrets.ALPINE_MAVEN_NAME }}
          ALPINE_MAVEN_SECRET: ${{ secrets.ALPINE_MAVEN_SECRET }}

      - name: "Read Version"
        if: github.event_name == 'workflow_dispatch'
        run: |
          set -e
          RELEASE_VERSION=$(./gradlew properties --full-stacktrace | grep "version:" | awk '{print $2}')
          if [[ -z "$RELEASE_VERSION" ]]; then
            echo "Error: unable to parse version from gradle properties."
            exit 1
          fi
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: "Create GitHub Release"
        if: github.event_name == 'workflow_dispatch' && !contains(env.RELEASE_VERSION, '-')
        # https://github.com/softprops/action-gh-release/releases
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: v${{ env.RELEASE_VERSION }}
          files: |
            build/libs/Itemize-${{ env.RELEASE_VERSION }}.jar
            plugin-api/build/libs/itemize-api-${{ env.RELEASE_VERSION }}.jar
          fail_on_unmatched_files: true
          make_latest: true
          prerelease: false
          draft: true
